python:
  version: "3.8"
  # Install our python package before building the docs
  install:
    - method: pip
      path: .

sphinx:
<<<<<<< Updated upstream
  fail_on_warning: true
=======
  fail_on_warning: true

  
formats:
  - pdf
  - epub
>>>>>>> Stashed changes
